### ISSUE TITLE
Add Google Maps integration

### ISSUE THREAD

**Issue by mattbarker016** [cuappdev/ithaca-transit-android#3]
Potentially add models for points and paths. See [Waypoint.swift](
https://github.com/cuappdev/tcat-ios/blob/master/TCAT/Model/Waypoint.swift) and [WalkPath.swift](https://github.com/cuappdev/tcat-ios/blob/master/TCAT/Model/WalkPath.swift)

**Comment by ningning621** [comment]
@djr277
