### ISSUE TITLE
Map out file structure

### ISSUE THREAD

**Issue by mattbarker016** [cuappdev/ithaca-transit-android#5]
For Sunday's meeting! 

> Decide the basic architecture of the app (which directory each file goes and what functions it performs) together during our Wednesday meeting, so that we can all start to work on different modules

We can assign different portions of the app, and get the ball rolling!

**Comment by abdullah248** [comment]
Not exactly file structure, but general flow for the application: Main activity which has a map. When you search it overlays on original map (possibly fragment). When you click on a location goes to a new activity/fragment that is completely separate. Allows you to choose start/end point and also displays possible methods. If you edit start/end, then stays in the same view does not go back to map. When you select a route, it goes back to the original main maps activity and overlays route on the bottom.

**Comment by ningning621** [comment]
@djr277 is this resolved now?
